[package]
name = "bubshayz/instanceutil"
description = "A utility module for working with instances."
authors = ["bubshayz"]
license = "MIT"
version = "1.0.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"