[package]
name = "bubshayz/matrixutil"
description = "A utility module for working with matrixes."
authors = ["bubshayz"]
license = "MIT"
version = "1.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"