[package]
name = "bubshayz/queue"
description = "A class for creating queues."
authors = ["bubshayz"]
version = "1.1.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.2.0"
Promise = "evaera/promise@4"