[package]
name = "bubshayz/numberutil"
description = "A utility module for working with numbers."
authors = ["bubshayz"]
version = "1.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"