[package]
name = "bubshayz/numberutil"
description = "A utility module for working with numbers."
authors = ["bubshayz"]
license = "MIT"
version = "1.0.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"