[package]
name = "bubshayz/enumlist"
description = "A class for creating enum lists."
authors = ["bubshayz"]
license = "MIT"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"